"""
Problem 2:

Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""

sum = 0

# Only add every 3rd Fibonacci number
x = 1
y = 1
z = x + y
while (z <= 4000000):
    sum += z;
    x = y + z
    y = x + z
    z = x + y

print(sum)
